apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: soam
build:
  local:
    push: false
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:latest"
  artifacts:
    - image: mosquitto
      context: mosquitto
    - image: simulator
      context: simulator
    - image: frontend
      context: frontend
    - image: backend
      context: backend
    - image: ingestor
      context: ingestor
    - image: spark
      context: spark
    - image: grafana
      context: grafana
    - image: prometheus
      context: prometheus
manifests:
  rawYaml:
    - k8s/*.yaml
deploy:
  kubectl: {}
  helm:
    releases:
      - name: soam
        remoteChart: oci://registry-1.docker.io/bitnamicharts/spark
        version: 6.3.16
        valuesFiles:
          - spark-values.yaml
portForward:
  - resourceType: service
    resourceName: soam-spark-master-svc
    namespace: default
    port: 80
    localPort: 8080
  - resourceType: service
    resourceName: frontend
    namespace: default
    port: 3000
    localPort: 3000
  - resourceType: service
    resourceName: backend-external
    namespace: default
    port: 8000
    localPort: 8000
  - resourceType: service
    resourceName: ingestor
    namespace: default
    port: 8001
    localPort: 8001
  - resourceType: service
    resourceName: neo4j
    namespace: default
    port: 7474
    localPort: 7474
  - resourceType: service
    resourceName: minio
    namespace: default
    port: 9000
    localPort: 9000

# Uncomment the following lines to enable port forwarding for Grafana and Prometheus
  # - resourceType: service
  #   resourceName: grafana
  #   namespace: default
  #   port: 3000
  #   localPort: 3001
  # - resourceType: service
  #   resourceName: prometheus
  #   namespace: default
  #   port: 9090
  #   localPort: 9091
