apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: backend:latest
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          env:
            - name: NEO4J_URI
              value: bolt://neo4j:7687
            - name: NEO4J_USER
              value: neo4j
            - name: NEO4J_PASSWORD
              value: verystrongpassword
            - name: SPARK_HOST
              value: spark-master
            - name: SPARK_PORT
              value: "7077"
            - name: SPARK_HISTORY
              value: http://spark-history:18080
            - name: MINIO_ENDPOINT
              value: minio:9000
            - name: MINIO_ACCESS_KEY
              value: minio
            - name: MINIO_SECRET_KEY
              value: minio123
            - name: MINIO_BUCKET
              value: lake
          volumeMounts:
            - name: spark-events
              mountPath: /tmp/spark-events
      volumes:
        - name: spark-events
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - port: 8000
      targetPort: 8000
  type: NodePort
