apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: backend
spec:
  serviceName: backend
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
        - name: wait-for-dependencies
          image: busybox:1.35
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c"]
          args:
            - |
              echo "Waiting for Neo4j to be ready..."
              until nc -z neo4j 7474; do
                echo "Neo4j is not ready yet. Waiting 3 seconds..."
                sleep 3
              done
              echo "Neo4j is ready!"

              echo "Waiting for Spark Master to be ready..."
              until nc -z soam-spark-master-svc 7077; do
                echo "Spark Master is not ready yet. Waiting 5 seconds..."
                sleep 5
              done
              echo "Spark Master is ready!"
      containers:
        - name: backend
          image: backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
            - containerPort: 41397
            - containerPort: 41398
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 2000m
              memory: 2Gi
          env:
            - name: NEO4J_URI
              value: bolt://neo4j:7687
            - name: NEO4J_USER
              value: neo4j
            - name: NEO4J_PASSWORD
              value: verystrongpassword
            - name: SPARK_HOST
              value: soam-spark-master-svc
            - name: SPARK_PORT
              value: "7077"
            - name: SPARK_DRIVER_HOST
              value: backend-0.backend
            - name: SPARK_UI_PORT
              value: "80"
            - name: MINIO_ENDPOINT
              value: minio:9000
            - name: MINIO_ACCESS_KEY
              value: minio
            - name: MINIO_SECRET_KEY
              value: minio123
            - name: MINIO_BUCKET
              value: lake
            # Database configuration  
            - name: DATABASE_URL
              value: sqlite:////app/data/feedback.db
            # Spark driver configuration for Kubernetes
            - name: SPARK_DRIVER_BIND_ADDRESS
              value: "0.0.0.0"
            - name: SPARK_DRIVER_PORT
              value: "41397"
            - name: SPARK_BLOCK_MANAGER_PORT
              value: "41398"
            # Application configuration
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: LOG_LEVEL
              value: "INFO"
          volumeMounts:
            - name: spark-events
              mountPath: /tmp/spark-events
            - name: backend-db
              mountPath: /app/data
      volumes:
        - name: spark-events
          emptyDir: {}
        - name: backend-db
          persistentVolumeClaim:
            claimName: backend-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  clusterIP: None # Headless service for StatefulSet
  selector:
    app: backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
    - name: spark-driver
      port: 41397
      targetPort: 41397
    - name: spark-blockmanager
      port: 41398
      targetPort: 41398
---
apiVersion: v1
kind: Service
metadata:
  name: backend-external
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
