apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-db-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: "local-path"