apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neo4j
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      containers:
        - name: neo4j
          image: neo4j:5.17.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7474
            - containerPort: 7687
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 2Gi
          env:
            - name: NEO4J_AUTH
              value: neo4j/verystrongpassword
            - name: NEO4J_PLUGINS
              value: '["apoc", "graph-data-science", "n10s"]'
            - name: NEO4J_server_config_strict__validation_enabled
              value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: neo4j
spec:
  selector:
    app: neo4j
  ports:
    - name: http
      port: 7474
      targetPort: 7474
    - name: bolt
      port: 7687
      targetPort: 7687
  type: NodePort
