global:
  scrape_interval: 15s

scrape_configs:
  # container stats
  - job_name: cadvisor
    static_configs:
      - targets: ['cadvisor:8080']

  # spark master & workers (built-in)
  - job_name: spark
    metrics_path: /metrics/prometheus
    static_configs:
      - targets: ['spark-master:8080', 'spark-worker-1:8081']  # add more workers if scaled

  # MinIO (optional)
  # docker run -d --name minio-exporter --net soam_default minio/prometheus-exporter
  - job_name: minio
    static_configs:
      - targets: ['minio-exporter:9300']

  # Mosquitto (optional) – needs exporter sidecar
  # - job_name: mosquitto
  #   static_configs:
  #     - targets: ['mosquitto-exporter:9234']
